name: assignment
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_core: ^3.13.0
  flutter_screenutil: ^5.9.3
  table_calendar: ^3.2.0
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.1.1
  hive_generator: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500

